Avoid segfault with wrong COM port
kees/scantool pull request #8
Opened 2021-08-19 15:11 UTC by Ircama

Avoid segmentation fault if a wrong COM port is set

2021-08-19 18:40 UTC, kees requested changes

2021-08-19 18:40 UTC, kees commented on serial.c
> +   if (fdtty < 0) {
This doesn't seem much better than segfaulting. :) What's the condition where this can happen? It seems like it'd be better for handle this a little more gracefully.

2021-08-19 18:42 UTC, Ircama commented on serial.c
> +   if (fdtty < 0) {
For FD_SET(), POSIX requires fd to be a valid file descriptor.

2021-08-19 18:50 UTC, kees commented on serial.c
> +   if (fdtty < 0) {
Sure, so why not just fail to do those things instead of quitting? Better yet, how did we get here with a -1 fdtty? That's the real bug, yes?

2021-08-19 20:11 UTC, Ircama commented on serial.c
> +   if (fdtty < 0) {
This happens when the COM port (e.g., pty, but I also think USB) is disabled while the program is running.

To reproduce the issue, apply the patch to enable pty ports, open a pty port served by a valid OBDII/ELM327 interface (e.g., use https://github.com/Ircama/ELM327-emulator), then after successful connection, press Sensor Data (should work), then Main menu, then close the pty port (e.g., terminate https://github.com/Ircama/ELM327-emulator), then press again Sensor data. If this patch is applied, you get:

```
write tty: Input/output error

Wrong serial COM port. Terminating program.
```

Otherwise, the following message is displayed:

```
write tty: Input/output error
*** buffer overflow detected ***: terminated
Shutting down Allegro due to signal #6
Aborted (core dumped)
```

I expect that if you unplug the USB port, the result will be the same.

2021-08-20 04:55 UTC, kees commented on serial.c
> +   if (fdtty < 0) {
Okay, cool. It seems that the correct fix here is to catch the issue as it happens (i.e. during the "write") and handle it gracefully instead of just shutting down.

2021-08-20 06:53 UTC, Ircama commented on serial.c
> +   if (fdtty < 0) {
OK I implemented and tested the new code

2021-12-02 08:33 UTC, merged